version: '3.2'
services:
  api:
    extends:
      file: docker-compose.base.yml
      service: api
    ports:
      - '${APP_PORT}:80'
    environment:
      XDEBUG_CONFIG: 'remote_host=${REMOTE_HOST} remote_enable=1'
      PHP_IDE_CONFIG: 'serverName=MiniSend'
      APP_ENV: 'local'

#host.docker.internal
  ui:
    extends:
      file: docker-compose.base.yml
      service: ui
    ports:
      - '3000:3000'
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    entrypoint: ['sh', '-c']
    command: ['yarn dev']

  redis:
    extends:
      file: docker-compose.base.yml
      service: redis

  mariadb:
    extends:
      file: docker-compose.base.yml
      service: mariadb
    ports:
      - '13306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  mailhog:
    extends:
      file: docker-compose.base.yml
      service: mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  yarn_cache:
    driver: 'local'

networks:
  devnet:
    driver: 'bridge'